SEARCH_DIR(d:\datama~1\if3\101161~1\03_tok~1\)
SEARCH_DIR(c:\dev-pas\units\)
SEARCH_DIR(c:\dev-pas\units\rtl\)
SEARCH_DIR(c:\dev-pas\bin\)
INPUT(
c:\dev-pas\units\rtl\wprt0.ow
d:\datama~1\if3\101161~1\03_tok~1\pembel~1.ow
)
GROUP(
c:\dev-pas\units\rtl\LIBPWI~2.AW
c:\dev-pas\units\rtl\LIBPST~1.AW
c:\dev-pas\units\rtl\libpdos.aw
c:\dev-pas\units\rtl\libpcrt.aw
c:\dev-pas\units\rtl\LIBPOB~2.AW
c:\dev-pas\units\rtl\LIBPSY~2.AW
)
